apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kubernetes-dashboard
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30200
  type: NodePort