apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kubernetes-dashboard
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      nodePort: 30100
      name: http
      targetPort: 3000
  type: NodePort